# Generated by Django 4.1.7 on 2023-06-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='asset_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
